name: Deploy to PROD EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/prod.pem
          chmod 600 ~/.ssh/prod.pem

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prod.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          cd ~/CICD-pipeline
          git reset --hard
          git pull origin main

          chmod +x deploy.sh
          ./deploy.sh

          echo "Deployment Completed!"
          EOF
